"""empty message

Revision ID: 298a228e12d4
Revises: 846c8454034c
Create Date: 2017-03-12 20:33:21.175094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298a228e12d4'
down_revision = '846c8454034c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'created_on')
    # ### end Alembic commands ###
