"""empty message

Revision ID: 5d2b02244bf4
Revises: 298a228e12d4
Create Date: 2017-03-13 02:08:30.764811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2b02244bf4'
down_revision = '298a228e12d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('email', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'email')
    # ### end Alembic commands ###
